#!/bin/bash

if [ ! -d /opt/evio/venv ]; then
    cd /opt/evio
    python3.9 -m venv venv
    source venv/bin/activate
    pip3 --cache-dir /var/cache/evio/ install wheel
    pip3 --cache-dir /var/cache/evio/ install eventlet==0.30.2 slixmpp requests simplejson ryu pyroute2 keyring
    deactivate
fi
systemctl daemon-reload
systemctl enable evio