#!/bin/bash

cd /opt/evio
python3.8 -m venv venv
source venv/bin/activate
pip3 --cache-dir /var/cache/evio/ install wheel
pip3 --cache-dir /var/cache/evio/ install eventlet==0.30.2 psutil slixmpp requests simplejson ryu pyroute2
deactivate
systemctl daemon-reload
systemctl enable evio