#!/bin/bash

systemctl -q is-active evio && systemctl -q stop evio || true
systemctl -q is-enabled evio && systemctl -q disable evio || true
rm -rf /opt/evio/venv
if [ -d /opt/evio/controller ]; then
  for dir in $(find /opt/evio/controller -type d -name __pycache__); do
     rm -rf "$dir"
  done
fi
exit 0

