#!/bin/bash

cd /opt/edge-vpnio
pip3 --no-cache-dir install virtualenv
virtualenv --python=python3 venv
source venv/bin/activate
pip3 --no-cache-dir install psutil sleekxmpp requests simplejson ryu
deactivate
systemctl daemon-reload
systemctl enable evio
